# Site settings
author: Jorge Ramirez
title: CLI Data Gem Portfolio Project 
header-img: img/home-bg.png
email: joramirez96@gmail.com
copyright_name: Jorge Ramirez
description: > # this means to ignore newlines until "baseurl:"
  The Process 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Jorge196

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
